.TH GRAPHITE 1
.SH NAME
graphite \- create a nice png template with google analytics data
.SH SYNOPSIS
.b graphite
[--name CURSIVE_NAME] 
.SH DESCRIPTION
.B graphite
creates an analytics.png file by taking data from your google analytics using it's api and renders them into a html template, which is saved as a .png with phantomjs
.SH OPTIONS
.tp
.BR \--N name
Creates a recursive "signature" on the file with whatever name you choose, be wary very long names can cause template issues

